type User @table {
  username: String!
  email: String!
  createdAt: Timestamp!
  displayName: String
  photoUrl: String
}

type Notebook @table {
  name: String!
  createdAt: Timestamp!
  description: String
  user: User
}

type Note @table {
  title: String!
  content: String!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  user: User
  notebook: Notebook
  lastEditedBy: User
}

type SharedNote @table(key: ["note", "sharedWithUser"]) {
  sharedAt: Timestamp!
  accessLevel: String!
  note: Note!
  sharedWithUser: User!
}

type Tag @table {
  name: String!
}

type NoteTag @table(key: ["note", "tag"]) {
  assignedAt: Timestamp!
  note: Note!
  tag: Tag!
}